[package]
name = "relnotes"
version = "0.1.0"
authors = ["Erin Power <xampprocky@gmail.com>"]

[dependencies]
reqwest = { version = "0.10", features = ["blocking", "json"] }
chrono = "0.4"
serde = "1"
serde_json = "1"
askama = "0.8"
